// src/frontend/component/Footer.jsx
import React from "react";

const TWITTER_URL = "https://twitter.com/_ytanaka_";
const GITHUB_URL = "https://github.com/ytanaka-/menthas";

export const Footer = () => {
  return (
    <>
      <div v-show="pages.length > 0" className="footer">
        <div className="footer-container">
          <div className="info1">
            <span>
              Menthas関連リンク:{" "}
              <a href="/privacy_policy">プライバシーポリシー</a>,{" "}
              <a href={TWITTER_URL}>開発者Twitter</a>,{" "}
              <a href={GITHUB_URL}>Github</a>
            </span>
          </div>
          <div className="info2">
            <span>
              Menthasはユーザビリティの改善や分析のためGoogleAnalyticsを使用しています
            </span>
          </div>
        </div>
      </div>
    </>
  );
};

// src/frontend/components/Footer.vue
<template>
  <div v-show="pages.length > 0" class="footer">
    <div class="footer-container">
      <div class="info1">
        <span>Menthas関連リンク: <a href="/privacy_policy">プライバシーポリシー</a>, <a href="https://twitter.com/_ytanaka_">開発者Twitter</a>, <a href="https://github.com/ytanaka-/menthas">Github</a></span>
      </div>
      <div class="info2">
        <span>Menthasはユーザビリティの改善や分析のためGoogleAnalyticsを使用しています</span>
      </div>
    </div>
  </div>
</template>

<script>

export default {
  name: 'Footer',

  data: () => ({
  }),
  computed: {
    pages() {
      return this.$store.getters.pages;
    }
  }
}
</script>

<style lang="stylus">
.footer
  width 100%
  height 60px

.footer-container
  max-width 930px
  margin 0 auto
  padding 12px
  border-top 1px solid #e0e0e0
  font-size 12px
  color #8C8C8C
  text-align: center

  .info2
    margin-top 7px

</style>
